version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: dataset-cleaning-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dataset-cleaning
    networks:
      - upload-service-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dataset-cleaning-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - upload-service-network

  # API Service
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: dataset-cleaning-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/server/node_modules
      - /app/shared/node_modules
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/dataset-cleaning
      - JWT_SECRET=your-secret-key
      - UPLOAD_DIR=/tmp/uploads
      - S3_BUCKET=your-dataset-bucket
      - S3_REGION=us-east-1
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - upload-service-network

  # Worker Service
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: dataset-cleaning-worker
    restart: always
    volumes:
      - .:/app
      - /app/worker/node_modules
      - /app/shared/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dataset-cleaning
      - S3_BUCKET=your-dataset-bucket
      - S3_REGION=us-east-1
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - upload-service-network

# Networks
networks:
  upload-service-network:
    driver: bridge

# Volumes
volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local